let num = 1000, deno = 20;

try{
    console.log(num/deno);
    console.log(a);

}
catch (error){
    console.log("An Error Caught");
    console.log("Error Message : " + error);
}

// try {
//     console.log(numerator / denominator);
//     console.log(a);
// }
// catch (error) {
//     console.log('An error caught');
//     console.log('Error message: ' + error);
// }